### ISSUE TITLE
Documentation for upgrade process

### ISSUE THREAD

**Issue by ascorbic** [piotrwitek/typesafe-actions#10]
Hi,
Thanks for this. It's really useful. I'm using it in [ignite-typescript-boilerplate](https://github.com/aerian-studios/ignite-typescript-boilerplate/), and ran into a problem with the API changes between 1.0.0-beta5 and 1.0.0-rc0, specifically the change from .type to getType(). It would be great if you could give some details about how to upgrade from ts-redux-actions to typesafe-actions, and if there are any other breaking changes.

**Comment by piotrwitek** [comment]
Hi @ascorbic, first of all thanks for the appreciations to the guide in your repo :)
Second I'll be glad to help you, could you please point me to the files where you're using `ts-redux-actions` in your repo?

**Comment by ascorbic** [comment]
Hi @piotrwitek . I've actually already upgraded our repo, thanks!

**Comment by piotrwitek** [comment]
@ascorbic that's  cool, I hope it wasn't too much of a hassle 😉 
I'll close the issue then.
Cheers!
