### ISSUE TITLE
createAsync action treats `any` as `void` for the failure payload type

### ISSUE THREAD

**Issue by amakhrov** [piotrwitek/typesafe-actions#117]
## Description
Example:
```
// define the action creation
export const fetchData = createAsyncAction(
  'FETCH_REQUEST',
  'FETCH_SUCCESS',
  'FETCH_FAILURE'
)<void, Models[], any>();

// usage
fetchData.request(); // OK
fetch.success(myModels); // OK
fetch.failure('arbitrary error'); // Type error: Expected 0 arguments, but got 1.
```

## Expected behavior
Instead, fetch.failure should be typed as `(payload: any) => void`, accepting a single argument

## Analysis
This seems to be caused by this code:
```
P extends Box<void>
    ? NoArgCreator<T>
    : PayloadCreator<T, Unbox<P>>
```
Somehow, `Box<any>` matches the `Box<void>` condition.

I was actually able to reproduce a similar behavior on Typescript playground ([link](https://www.typescriptlang.org/play/#src=type%20Box%3CT%3E%20%3D%20%7B%20v%3A%20T%20%7D%3B%0D%0Atype%20Test%3CT%20extends%20Box%3Cany%3E%20%3D%20Box%3Cvoid%3E%3E%20%3D%0D%0A%20%20%20%20T%20extends%20Box%3Cvoid%3E%20%3F%0D%0A%20%20%20%20%20%20%20%20()%20%3D%3E%20void%20%3A%0D%0A%20%20%20%20%20%20%20%20(a%3A%20T)%20%3D%3E%20T%3B%0D%0A%0D%0Alet%20t%3A%20Test%3CBox%3Cany%3E%3E%3B%0D%0At(1)%0D%0A))

**Comment by piotrwitek** [comment]
Hey @amakhrov, that's a great bug report.
I'll need to add a test case for this scenario and I'll work on the fix ASAP

**Comment by piotrwitek** [comment]
This should fix it: 
```ts
type Box<T> = { v: T };
type Test<T extends Box<any> = Box<void>> =
    T extends Box<infer TT> ? TT extends void ? 
        () => void :
        (a: TT) => TT
        : never

let t: Test<Box<any>>;
t(1)
```
