### ISSUE TITLE
 Cannot find module 'MyTypes'

### ISSUE THREAD

**Issue by ToonvanStrijp** [piotrwitek/typesafe-actions#126]
I'm getting this error but don't know how to resolve it
![image](https://user-images.githubusercontent.com/11893063/53962243-daddba80-40ea-11e9-93c8-c43e3762b6a9.png)

This is what my module definition looks like:
```typescript
import { ActionType, StateType } from 'typesafe-actions';

declare module 'MyTypes' {
  export type Store = StateType<typeof import('./index').default>;
  export type RootAction = ActionType<typeof import('./root-action').default>;
  export type RootState = StateType<typeof import('./root-reducer').default>;
}
```

The strange thing is that when I change it to this:
```typescript
import { ActionType, StateType } from 'typesafe-actions';

declare module 'MyTypes' {
  export const Test = 'test';
}
```

Then the modules gets recognized.

**Comment by piotrwitek** [comment]
Hey, sorry this is not library issue, I have to close it. You can always ask on gitter.
