### ISSUE TITLE
Documentation : isOfType instead isTypeOf

### ISSUE THREAD

**Issue by JackJackNg** [piotrwitek/typesafe-actions#127]
## Description
Correct documentation: isOfType instead of isTypeOf
![image](https://user-images.githubusercontent.com/30189960/54327690-f21a2c00-4645-11e9-8603-c36f4cb64f17.png)

## CodeSandbox to help you reproduce issue in isolation
> Please use this sandbox as an isolated environment to reproduce the bug: https://codesandbox.io/s/github/piotrwitek/typesafe-actions/tree/master/codesandbox

## Project Dependencies
- Typesafe-Actions Version: X.X.X
- TypeScript Version: X.X.X
- tsconfig.json:

## Environment
- Browser and Version: XXX
- OS: XXX
- Node Version: XXX
- Package Manager and Version: XXX

**Comment by piotrwitek** [comment]
Thanks for the fix!
