### ISSUE TITLE
Array.prototype.includes has problems on IE even with core-js

### ISSUE THREAD

**Issue by snackycracky** [piotrwitek/typesafe-actions#133]
<img width="1432" alt="Screenshot 2019-04-05 16 02 13" src="https://user-images.githubusercontent.com/144498/55633412-a37f2e00-57bc-11e9-8bfc-5169f9a26083.png">

**Comment by piotrwitek** [comment]
@snackycracky which IE ver. are we talking about?

**Comment by piotrwitek** [comment]
Closing as there is no response, I'll consider reopening when there is more details

**Comment by snackycracky** [comment]
Its IE 11. I reverted back to version 3.0.0 and it worked again.

**Comment by piotrwitek** [comment]
@snackycracky just tested the codesandbox project with typesafe-action@3.3.0 in IE11 and working great, how is that?

![Screenshot 2019-04-11 at 6 33 39 PM](https://user-images.githubusercontent.com/739075/55974802-b4caad80-5c88-11e9-8b3c-977ca9167e56.png)

**Comment by piotrwitek** [comment]
You need to provide some reproducible leads to make it worth the time

**Comment by snackycracky** [comment]
ok cool, did you try 4.0.0 ? Then it breaks in my experience.

**Comment by snackycracky** [comment]
4.0.0 is what I was targeting with this ticket. Sorry if it wasn’t clear.

**Comment by piotrwitek** [comment]
Ok thanks, I'll check that

**Comment by piotrwitek** [comment]
@snackycracky ok I did tested with v4.0.0 and it works with IE11. I just added `@babel/polyfill` to the codesanbox project.

So it's confirmed `typesafe-actions` require `@babel/polyfill` to be compatible with IE11.

![Screenshot 2019-04-11 at 6 54 39 PM](https://user-images.githubusercontent.com/739075/55976130-bcd81c80-5c8b-11e9-8122-421540731700.png)

**Comment by denyo** [comment]
Since `@babel/polyfill` is deprecated you can also use
```
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';
```
or use `import 'core-js/stable';` directly.

**Comment by piotrwitek** [comment]
Thanks @denyo, feel free to send a PR to update the sandbox project.
