### ISSUE TITLE
infer state object type from combined reducers with connected-react-router

### ISSUE THREAD

**Issue by Brian611** [piotrwitek/typesafe-actions#134]
## Description
MyTypes RootState cannot infer state object type from a combined reducer function with router history passed to it.

## Steps to Reproduce
// root-reducer.ts
```ts
import { connectRouter } from 'connected-react-router'
import { History } from 'history';

const rootReducer = (history: History) => combineReducers({
  router: connectRouter(history),
  login: loginReducer,
});
export default rootReducer;

// types.d.ts
export type RootState = StateType<typeof import('./root-reducer').default>;

// login.tsx
const mapStateToProps = (state: RootState) => ({
    mobileNumber : state.login.mobileNumber
});
```
## Error
// login.tsx

"state expected 2 arguments but received none

## Expected behavior
from mapStateToProps should be able to access variables from my RootState with ease

## Project Dependencies
- "typesafe-actions": "3.3.0"
- "typescript": "3.4.1"
- "connected-react-router": "^6.3.2"

**Comment by piotrwitek** [comment]
@Brian611 have you tried recent version? 4.0.0

**Comment by piotrwitek** [comment]
You're using it incorrectly. You should pass a reducer type not some custom higher order function as a type parameter.

**Comment by Brian611** [comment]
connect-react-router is a replacement for react-redux-router(it is now deprecated). A lot of people will be using this library and this is how you setup it up from the docs so i would suggest this feature to be included in future.

**Comment by piotrwitek** [comment]
export type RootState = StateType<typeof ReturnType<import('./root-reducer').default>>;

**Comment by Methuselah96** [comment]
@Brian611 Or just `export type StoreState = StateType<ReturnType<typeof rootReducer>>;`.

**Comment by NickisyourFan** [comment]
> export type RootState = StateType<ReturnType<typeof import('./root-reducer').default>>;

Thanks! This helped me out a lot and learned about ReturnType
