### ISSUE TITLE
Typescript: handleAction action has type never for action with identical type

### ISSUE THREAD

**Issue by vikhotey** [piotrwitek/typesafe-actions#149]
## Description
I have 2 actions with same types but different action type and when I handle second action it has `never` type
```ts
export const fetchAdverts = createAsyncActions<
  {
    forUser?: boolean;
    search: { offset: number; limit: number; title?: string };
  },
  { data: Advert[]; count: number },
  void
>(`${REDUCER_KEY}fetchAdverts`);

export const fetchMoreAdverts = createAsyncActions<
  {
    forUser?: boolean;
    search: { offset: number; limit: number; title?: string };
  },
  { data: Advert[]; count: number },
  void
>(`${REDUCER_KEY}fetchMoreAdverts`);
```

Add handlers for this actions:
```ts
export const reducer = createReducer(initState)
  .handleAction(fetchAdverts.success, (_, action) =>
    action.payload.data.map(item => item.id)
  )
  .handleAction(
    fetchMoreAdverts.success,
    (state, action) => [
      ...state,
      ...action.payload.data.map(item => item.id)
    ]
  )
```

<img width="663" alt="Screen Shot 2019-05-12 at 3 58 24 PM" src="https://user-images.githubusercontent.com/37971386/57582560-da88e380-74ce-11e9-9b21-4ca0796c2a1d.png">
<img width="491" alt="Screen Shot 2019-05-12 at 3 58 35 PM" src="https://user-images.githubusercontent.com/37971386/57582561-da88e380-74ce-11e9-9761-27b66259fbf1.png">

**Comment by piotrwitek** [comment]
This is incorrect usage, please read the tutorial section carefully especially Constants: https://github.com/piotrwitek/typesafe-actions#constants
