### ISSUE TITLE
Unable to use an object for defining types with createAction

### ISSUE THREAD

**Issue by mwq27** [piotrwitek/typesafe-actions#15]
I was wondering if this is the intended use.
```js
export const actions = {
 login: createAction(types.LOGIN_REQUEST, (email: string, password: string) => ({
    type: types.LOGIN_REQUEST,
    payload: { email, password },
  })),
  loginSuccess: createAction('AUTH/LOGIN_SUCCESS', (authData: any) => ({
    type: 'AUTH/LOGIN_SUCCESS',
    payload: { authData },
  })),
...
```
With the `login` action above, I get this output with `returnsOfActions`:
```js
const returnsOfActions = Object.values(actions).map($call);
type AppAction = typeof returnsOfActions[number];
/**** Here's what the types looks like (hovering my mouse over returnsOfActions **/
const returnsOfActions: ({
    type: string;
    payload: {
        email: string;
        password: string;
    };
} | {
    type: "AUTH/LOGIN_SUCCESS";
    payload: {
        authData: any;
    };
```
The type for the login_request action returns as `string`, and not the actual value of `types.LOGIN_REQUEST`.  Is there any way I can continue using my `types` object, or do I need to use the actual value when I use `createAction`?

Thanks

**Comment by sylvanaar** [comment]
Can you show the code for `types.LOGIN_REQUEST` including it's type definition if you wrote one. You don't have to use a raw string - but what you supply has to have a literal string type - not just a string, and there are a few ways that you could end up widening your literal string type, like creating it with concatenation.

**Comment by mwq27** [comment]
Here's my types object: 

```js
export const types = {
  AUTO_LOGIN: 'AUTH/AUTH_AUTO_LOGIN',
  SIGNUP_REQUEST: 'AUTH/SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'AUTH/SIGNUP_SUCCESS',
....
```

I don't have a typedef for that object.

**Comment by mwq27** [comment]
Do i need to do this: 
```ts
type MyTypes = {
  AUTO_LOGIN: 'AUTH/AUTH_AUTO_LOGIN',
  SIGNUP_REQUEST: 'AUTH/SIGNUP_REQUEST',
....
export const types: MyTypes = {
  AUTO_LOGIN: 'AUTH/AUTH_AUTO_LOGIN',
  SIGNUP_REQUEST: 'AUTH/SIGNUP_REQUEST',
...
```

**Comment by mwq27** [comment]
Thank you, I switched to using an enum.  Thanks for your help.
