### ISSUE TITLE
property payload does not exist on action generated by action-enhancer

### ISSUE THREAD

**Issue by maheffa** [piotrwitek/typesafe-actions#154]
## Description
The field `payload` cannot be accessed in the reducer, even if the action is generated using the enhancer, or the `createStandardAction` utility.
This is also the case for the current version of the code on [codesandbox](https://codesandbox.io/s/github/piotrwitek/typesafe-actions/tree/master/codesandbox)

*///features/todos/reducer.ts:20*
![image](https://user-images.githubusercontent.com/3521608/57961452-5fc92980-790f-11e9-954d-bcf79b0497dc.png)

## Steps to Reproduce
*simple-action-reducer.ts*
```typescript
import { createAction, createReducer } from 'typesafe-actions';

export const add = createAction('todos/ADD', action => {
  return (title: string) => action({ id: 24, title, completed: false });
});

const counterReducer = createReducer([])
  .handleAction(add, (state, action) => state.concat(action.payload));
```

```shell
~$ tsc simple-action-reducer.ts

simple-action-reducer.ts:8:56 - error TS2339: Property 'payload' does not exist on type '{}'.

8   .handleAction(add, (state, action) => state + action.payload);
```

## Expected behavior
`payload` field should be recognized by the compiler.

## Project Dependencies
- Typesafe-Actions Version: 4.3.0
- TypeScript Version: 3.4.5
- tsconfig.json:
```json
{
  "compilerOptions": {
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "outDir": "./dist/",
    "noImplicitAny": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "extendedDiagnostics": true,
    "typeRoots": ["./app/@types"],
    "lib": ["es2015", "dom"],
    "rootDirs": [
      "app",
      "translations",
      "node_modules"
    ]
  },
  "include": ["./app/"],
  "exclude": ["./node_modules"]
}
```

**Comment by piotrwitek** [comment]
Hey @maheffa, 
I think you have missed this section: https://github.com/piotrwitek/typesafe-actions#extending-internal-types-to-streamline-type-usage-with-typesafe-actions

I have updated API docs to be clearer about createReducer API and linked to the relevant tutorial section.

PS: codesandbox is not supporting all TS features and it's using v3.3, best to use your local env to reproduce type issues

**Comment by Kenpa** [comment]
Hey @piotrwitek,
I am also facing this issue on v4.4.0 and typescript 3.4.5.
The current sandbox version is suffering the same issue as well (i cloned the project and ran it in my local env)

**Comment by piotrwitek** [comment]
Hey @Kenpa 
I have just checked a clean installation of codesandbox in the recent master and there is no such issue. Please doublecheck on recent please.

**Comment by Kenpa** [comment]
My bad, misread my typescript version, was running an old one...
Sorry for that

**Comment by piotrwitek** [comment]
No biggie 😉
