### ISSUE TITLE
CreateAsyncAction with mapper

### ISSUE THREAD

**Issue by maheffa** [piotrwitek/typesafe-actions#157]
I saw in the specs a way create async actions with custom request, success and failure implementation, but they are all commented out.

Will it be soon available?

**Comment by piotrwitek** [comment]
@maheffa this will be available real soon: https://github.com/piotrwitek/typesafe-actions/issues/143
There is a new async action api

**Comment by maheffa** [comment]
Great! Thanks. Will keep my eyes open.

**Comment by maheffa** [comment]
@piotrwitek 
This looks very good to me. I'm currently refactoring a codebase that has a lot of redux-actions where payloads are derived from request result.

Would also help to know an estimation of when will it be available (if possible of course), if I can wait or should proceed to work with what is currently available.

**Comment by piotrwitek** [comment]
I have planned to finish it and publish new version end of this week or sooner if possible.
