### ISSUE TITLE
IE falls over on default parameters

### ISSUE THREAD

**Issue by ee0pdt** [piotrwitek/typesafe-actions#159]
## Description
IE11 throws a syntax error when parsing built version of validation.ts

![image](https://user-images.githubusercontent.com/6094917/58562175-a4fb2e80-8220-11e9-96a7-d5f3c37517c4.png)

The default value set on the argPosition parameter seems to the the issue here.
```
export function checkIsEmpty(arg: unknown, argPosition: number = 1) {
  return arg == null;
}
```

## Steps to Reproduce
1. Create an app importing typesafe-actions
2. Attempt to run it in IE11

**CodeSandbox to help you reproduce issue in isolation**
Attempted to reproduce here, is erroring with similar message but not identical to prod issue https://codesandbox.io/s/typesafeactionsieissue-lhfbc

## Expected behavior
Should run fine (assuming IE polyfills added as per docs)

## Suggested solution(s)
Transform the default parameters on build

## Project Dependencies
- Typesafe-Actions Version: 4.2.1
- TypeScript Version: 3.3.3333

- tsconfig.json:

```"compilerOptions": {
    "baseUrl": ".",
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es2015", "es2017", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "typeRoots": ["./@types", "./node_modules/@types"],
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": false,
    "allowSyntheticDefaultImports": true
  },
```

In our production app we are building with parcel (pipeline is: .tsx -> tsc -> .js -> babel)

## Environment (optional)
- Browser and Version: IE 11
- OS: Windows 10

**Comment by piotrwitek** [comment]
@ee0pdt please use most recent version, there was a fix for this.
