### ISSUE TITLE
createAction doesn't support Symbol type

### ISSUE THREAD

**Issue by AlexeiGontarCyber** [piotrwitek/typesafe-actions#16]
We are trying to use typed-actions in our project but according to our code style, we are using symbols everywhere. It would be good if type-actions will support this use case.

**Comment by piotrwitek** [comment]
Hi @AlexeiGontarCyber,
So you would like to use Symbol instead of string type right? I'm wondering if that make sense because the main benefit here is a discrimination of "union" by using string discriminant.
Have you tested the scenario that Symbols is able to be used as discriminant instead of string literal type?

**Comment by piotrwitek** [comment]
@AlexeiGontarCyber I would look at this issue and try to figure out the solution, would you please post a code example here of how you would like to use it when Symbols would be supported, so I have some kind of reference that I can use.

**Comment by AlexeiGontarCyber** [comment]
@piotrwitek thanks for your efforts.
Well, let me first provide some motivation why we are using Symbols in our project instead of strings. We have a big project and it's hard to create the unique type strings. We know that it's not recommended because it's impossible to serialize them.

About code samples:
I am not sure that I can provide them because it's nothing special. To be ownest I was wondered that there is no Symbol choice out of the box.
I could say that we would like to have type inference in switch case described [here](https://github.com/piotrwitek/typesafe-actions#reducer-switch-cases).
Also, could you provide motivation or some useful links with RootAction approach, please?

**Comment by piotrwitek** [comment]
### Motivation for RootAction
The biggest advantage is that you won't need to declare explicit type declaration for your actions and move them around through various application layers (e.g. reducers thunks, sagas, epics, middlewares), like below:

```ts
// this is bad: generate excess boilerplate for type declaration
export interface AddActionType {
  type: 'ADD';
  payload: number,
}
const addActionCreator: (amount: number) => AddActionType = ...
...
// you'll need to declare this for each one action, it will quickly get really tedious and verbose...

// now you'll need to join them in union, if you forget one you'll get cryptic errors from compiler
export type ActionUnion = AddActionType | ...

// finally you can import, but still you need to be explicit when using them
import { ActionUnion, AddActionType } from ...
const epic = (action$: ActionUnion, store: Store) =>
  action$
    .filter(action => action.type === 'ADD')
    // now you need to make type explicit manually
    .map(action: AddActionType => ...)
    ...
```

Instead you should do doing this other way around, be deriving your types from implementation.
To do this you will need to just create `RootAction` union type, by deriving it's type declaration directly from action creators implementation using type inference mechanism.
```ts
// just use createAction API
// New v2.0 API will have a few simplification to remove redundant params
// actions.ts
export const addAction = createAction<number>('ADD');
export const subtractAction = ...

// now very easily get RootAction union type, and never be bothered again, all actions from actions.ts file will be added automatically
// NOTE: this is a new API available soon with TS v2.8 release
import * as actions from './actions.ts'
type RootAction = ActionsUnion<typeof actions>;
```

Then in any place that you want to use some action you will use `if` / `switch` statements or `getType` / `isActionOf` helpers, this will narrow the union to specific type that you need in the following code block without searching for it's type somewhere else and importing to this place.

```ts
// now everything is automatically derived from the implementation
import { RootAction } from ...
const epic = (action$: RootAction, store: Store) =>
  action$
    .filter(isActionOf(addAction))
    // don't need to be explicit anymore, type is correctly narrowed down to addAction type only
    .map(action => ...)
    ...
```

Also if you try to change action creator implementation, your action type will update automatically and propagate downstream throughout your application, pointing out type errors in every place you are using this action, of course refactoring works just fine and you could use that in the first place :)

This will decrease your types maintenance efforts tremendously while completely eliminating surface for type errors (strict checking is mandatory), and it is really invaluable for scaling your Redux architecture when your action count is starting to go up above 50.

**Comment by piotrwitek** [comment]
### WIP - after API v2.0.0 is released
- `createSymbolAction` will give you a new API to use Symbols instead of strings for action type, and still benefit from discriminated union types with complete type safety
```ts
import { createSymbolAction } from 'typesafe-actions';
import { RootAction } from './types';

const INCREMENT = Symbol(1);
const ADD = Symbol(2);

export default (state = 0, action: RootAction) => {
  switch (action.type) {
    case INCREMENT: {
      return state + 1;
    }
    case ADD: {
      return state + action.payload;
    }
  }
};

// NB: mandatory to fill in generic symbol type arg, because symbol loses uniqueness when inferred (possibly a bug in typescript@rc)
export const increment = createSymbolAction<typeof INCREMENT>(INCREMENT);
export const add = createSymbolAction<typeof ADD, number>(ADD);
```

**Comment by piotrwitek** [comment]
closing as this seems like too much effort for too little gain (maybe a few % of all use-cases), if someone really needs such custom solution he can contribute. I have a lot of different plans and will not have time to implement this feature on my own

**Comment by piotrwitek** [comment]
I added support for every API to support Symbol type, but it will NOT be typesafe, you'll have to assert the type to string literal.

Regarding Type-safe Support for Symbols I have a lot of different plans and will not have time to implement this feature on my own (mostly because it covers only a few % of all use-cases), if someone really needs such custom solution he could contribute, there is already much of the ground work done, and it needs to be finalized and added some tests to confirm it's working as expected.
