### ISSUE TITLE
bindActionCreators doesn't work with PayloadAction and typed dispatch

### ISSUE THREAD

**Issue by goszczynskip** [piotrwitek/typesafe-actions#163]
## Description

`bindActionCreators` doesn't work with `PayloadAction` and typed `dispatch`

## Steps to Reproduce

Create following code in playground:
```
const mapDispatchToProps = (dispatch: Dispatch<Types.RootAction>) =>
  bindActionCreators(
    {
      onIncrement: countersActions.increment,
    },
    dispatch
  );
```

Look into `src/features/todos/components/TodoList.tsx`, I've prepared it there.
~https://codesandbox.io/embed/typesafeactionsreferenceproject-8g0tx~

## Expected behavior

`bindActionCreators` should accept typed `dispatch`

## Project Dependencies
- Typesafe-Actions Version: 4.4.0
- TypeScript Version: 3.5.1

Edit: 

fixed sandbox link:

https://codesandbox.io/s/typesafeactionsreferenceproject-8g0tx

**Comment by piotrwitek** [comment]
Hey @goszczynskip 
Sorry, but your issue has nothing to do with typesafe-actions.
It's because you're trying to use React Dispatch with Redux Dispatch which are not compatible.
Please check their type declarations for details. React is returning void while redux is returning action type.

**Comment by goszczynskip** [comment]
Hey @piotrwitek 
Thanks for fast response. You are totally right. Mea culpa
