### ISSUE TITLE
The library becomes unusable with a large number of action creators.

### ISSUE THREAD

**Issue by semenovDL** [piotrwitek/typesafe-actions#164]
## Description
With adding of new action creators number of generated types and memory consumption increases exponentially.

With 100 action creators typescript compiler generate 8M types and requires about 5Gb of ram.

## Steps to Reproduce

I create a repository with benchmarks that show this bug.

https://github.com/semenovDL/typesafe-actions-oom

## Expected behavior
Expect linear increasing of generated types.

## Suggested solution(s)
Fixes in type definitions.

## Project Dependencies
- Typesafe-Actions Version: 4.4.0
- TypeScript Version: 3.5.1

## Environment (optional)

- OS: Mac os Mojave (10.14.4)
- Node Version: v10.15.3
- Package Manager and Version: yarn 1.15.2

**Comment by piotrwitek** [comment]
Hey @semenovDL,
Thanks for your report and excellent reproduction case.
I'll take a look and try to identify the source of the performance issue.

**Comment by oozusta** [comment]
As a workaround I locally replaced createAsyncAction with 

export function createAsyncAction(request: string, success: string, failure: string) {
  return <T1, T2, T3>() => ({
    request: createStandardAction(request)<T1>(),
    success: createStandardAction(success)<T2>(),
    failure: createStandardAction(failure)<T3>(),
  });
}

and memory usage went from ~3.6GB to ~800MB. I'm losing some of the magic, but it's working for now without any need for a syntax change.

**Comment by hsz** [comment]
Having 20 `createAsyncAction` also causes this memory issue.
Converting those into 60 separated `createStandardAction` didn't help.

@piotrwitek Any progress on that?

**Comment by piotrwitek** [comment]
Yes, I have identified the issue and found the solution by simplifying some conditional types.

I have integrated performance tests from @semenovDL repo into "typesafe-actions" (thanks for a great template @semenovDL ❤️ ). Thanks to that I was able to identify the issues and confirm the solution is working

I should be able to release the fix today.

**Comment by semenovDL** [comment]
@piotrwitek thanks for the awesome work you have done.
