### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by zdila** [piotrwitek/typesafe-actions#168]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24140%20Funded-%2300A156.svg" />](https://issuehunt.io/r/piotrwitek/typesafe-actions/issues/168)

## Description

Cmpiling application with couple of reducers (~20) and action creators (~200) takes 2 GB RAM and requires passing `--max-old-space-size` to node when invoking `tsc`. Before fixing #164 it was much worse but it is still unuseable.

## Steps to Reproduce
1. Download and unpack https://drive.google.com/file/d/1FUzk5NeRfxUvwd4eXCxIFcb7Scmvh9D4/view?usp=sharing
2. run `npm i`
3. run `node --max-old-space-size=8192 ./node_modules/.bin/tsc --diagnostics`
4. See the result

## Expected behavior

Compilation of such project should be a piece of cake ;-) 

## Suggested solution(s)

Improve types or identify bug in TypeScript.

## Project Dependencies
- Typesafe-Actions Version: 4.4.1
- TypeScript Version: 3.5.2
- tsconfig.json: included in the tgz

## Environment (optional)
- OS: Debian Linux Buster
- Node Version: 12.4.0
- Package Manager and Version: npm 6.9.0

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $140.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($140.00)
### Submitted pull Requests
- [#171 #168](https://issuehunt.io/r/piotrwitek/typesafe-actions/pull/171)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/piotrwitek/typesafe-actions/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by hsz** [comment]
I can confirm that as well. Cold start of `tsc` still takes too much of the resources and time.

**Comment by mmalicki** [comment]
Probably related to this, I noticed when I changed all my reducers from standard switch case to createReducer, compiler typechecking and autocomplete slowed down noticably to the point where it's painful to use

**Comment by zdila** [comment]
@mmalicki that was actually also my case

**Comment by piotrwitek** [comment]
Thanks for the reproduction case 👍. I have confirmed an issue and will be working on that.

**Comment by hilkeheremans** [comment]
I can confirm the issue. Thanks so much for looking into it!

**Comment by piotrwitek** [comment]
PR is ready, now it's infinitely scalable. will release a new version tomorrow.

@zdila You can test it now using the following in your project to confirm:
`npm i piotrwitek/typesafe-actions##168`

![Screen Shot 2019-06-24 at 3 01 13 AM](https://user-images.githubusercontent.com/739075/59984660-8c6a1280-962c-11e9-868c-359375e8551d.png)

**Comment by zdila** [comment]
@piotrwitek thanks, but with `npm i piotrwitek/typesafe-actions##168` there is no more `dist` in `node_modules/typesafe-actions`.

**Comment by piotrwitek** [comment]
@zdila you can build the project locally and copy the dist folder or wait for me to release under the next branch in a few hours

**Comment by piotrwitek** [comment]
Published on npm as `@next`

**Comment by hsz** [comment]
Shouldn't that be released as v4.5.0 since it's a major performance issue?

**Comment by piotrwitek** [comment]
There is a breaking change in the API and I'm respecting semver.
But I might consider it if that is something critical to the majority of the users.

**Comment by hsz** [comment]
After upgrading to @next release, project hangs on tsc again with memory leak at the end (19x createAsyncAction, 1x createStandardAction).
`4.4.2` is working fine.
What can I do to provide you more details?

**Comment by zdila** [comment]
In my case `typesafe-actions@next` works now fine on [my project](https://github.com/FreemapSlovakia/freemap-v3-react). Thanks Piotr.

**Comment by piotrwitek** [comment]
@hsz take a look at great reproduction example from @zdila above and try to isolate the issue in your project the same way. Only this way we can confirm the issue is on our end and not within your application setup.
