### ISSUE TITLE
"Can't find variable: t" error on react native production build

### ISSUE THREAD

**Issue by alexbeckwith** [piotrwitek/typesafe-actions#169]
## Description
Using expo/react-native with version 4.4.1, production builds produce the above error. Seems like the same thing as [151](https://github.com/piotrwitek/typesafe-actions/issues/151)?

## Steps to Reproduce
1. Create expo app via `expo init {appname}`
2. `yarn add typesafe-actions@4.4.1`
3. Create action creator with `createStandardAction` and a reducer using `getType`
4. Run production build with `expo r --no-dev`

## Project Dependencies
- Typesafe-Actions Version: 4.4.1
- TypeScript Version: 3.4.5
- expo-cli version 2.19.2
- tsconfig.json:
```
{
  "compilerOptions": {
    "noEmit": true,
    "lib": ["dom", "esnext"],
    "jsx": "react-native",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "skipLibCheck": true
  }
}
```

- babel.config.js
```
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
  };
};
```

## Environment (optional)
- React Native: 0.59.8

**Comment by robertying** [comment]
Confirmed it was introduced in 4.4.1, downgrading to 4.4.0 resolves the issue.

**Comment by piotrwitek** [comment]
I found the root issue. Rollup dependency introduced a breaking change between 1.13 => 1.14, so emitted bundle code is changed:

1.13:
```ts
function n(n, t) {
  return void 0 === t && (t = 1), null == n;
}
```

1.14:
```ts
function n(n, t) {
  return null == n;
}
```

I will downgrade and lock rollup dependency until further investigation and viable solution is found.
