### ISSUE TITLE
suggestion: a default value for createAction with payload and meta

### ISSUE THREAD

**Issue by Jack-Works** [piotrwitek/typesafe-actions#17]
There should be a 
```
actionCreator<P, M>(type: ...): (Payload: P, Meta: M) => {type: ..., payload: P, meta: M}
```

**Comment by piotrwitek** [comment]
Hi,
Please explain what you are trying to achieve, what are the benefits from this and the example usage.

**Comment by Jack-Works** [comment]
const aNormalAction = actionCreator<number>("normal")

aNormalAction(2)
// I get {type: "normal", payload: 2}

Benefits here is we can create a simple action without repeating (...) => ({type: ..., payload: ...})

**Comment by piotrwitek** [comment]
Ah ok, so you basically want an escape hatch for a payload with type `any`, I need to think about it because the goal here is to have a strictly typed experience.
actionCreator without payload is specifically designed to show an error when you try to provide some input parameter and this is a good thing, because it's a TS library focused on limiting the developers errors and using your actions in incorrect way that you designed them in the first place.

**Comment by Jack-Works** [comment]
What? No, I don't want "any" either.

I want to provide a type parameter to actionCreator, and then a typed function is return, like this
```ts
function actionCreator<Payload, Type extends string>(type: Type, creatorFn: (payload: Payload) => ({ type: Type, payload: Payload }) = payload => ({ type, payload }))
```

**Comment by Jack-Works** [comment]
With this approach, I can get a typed action but without provide a creatorFn (well, this is for simple actions)

**Comment by piotrwitek** [comment]
Ok but what you want to do is technically impossible, if you don't provide a payload type when invoking  a higher order function how type inference is supposed to get the payload type?
Have you tested it?
If yes then please show me the reference implementation of actionCreator function only for this specific case, should be easy.

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/36932641-e9a6c504-1f06-11e8-9204-3c4e69396d04.png)
Alright, no filling generics type? Then it becomes impossible now

**Comment by piotrwitek** [comment]
@Jack-Works At least IMO there shouldn't be with the current API because that would be breaking change, maybe we could think about adding a new API but it should be generic enough to handle most of possible use cases, because I don't want to end up with a separate creator for each use case.

**Comment by piotrwitek** [comment]
Also I can see that the type string literal will lose it's type (and become `any`) if you do not explicitly provide it as a generic type argument, which is cumbersome.

**Comment by Jack-Works** [comment]
Yes... If modify createAction directly to support explicit `payload` type, `type` will be `any`...

**Comment by piotrwitek** [comment]
I'm about to experiment if it would be possible to infer the `type` literal type just from argument using the newest infer mechanics from conditional types, I guess that it should work, but I need to make sure. That would simplify API and keep it DRY
