### ISSUE TITLE
Type assertion on the whole action

### ISSUE THREAD

**Issue by farzadmf** [piotrwitek/typesafe-actions#19]
Hi,

I just found out about your library, and I think it is what I have been looking for to substantially reduce boilerplate code for actions and action creators; thank you!

Creating actions (using `createAction`) and `switch`ing on them (using `getType`) in the reducer works fine, but I was wondering if there's a way to do type checking for a method that expects a specific kind of action.

Example of my actions (I'm using lodash for `values` and `map`):

```ts
export enum ActionTypes {
  GetCameras = 'GET_CAMERAS',
  GetCamerasSuccss = 'GET_CAMERAS_SUCCESS',
}

export const cameraActions = {
  getCameras: createAction(ActionType.GetCameras, ( /*...*/ ) => ({
    type: ActionTypes.GetCameras,
    /* payload: ... */
  }),
  getCamerasSuccess: createActionTypes.GetCamerasSuccess, (/*...*/) => ({
    type: ActionTypes.GetCameras,
    /* payload: ... */
  }),
};

const returnsOfActions = _.map(_.values(actions), $call));
export type CameraAction = typeof returnsOfActions[number];
```

Maybe a good example would be a case where the reducer wants to call another method for a specific action type, for example, in my reducer:

```ts
export const reducer = (state = initialState, action: CameraAction) => {
  case getType(cameraActions.getCameras):
    return state; /* ... */
  case getType(cameraActions.getCamerasSuccess):
    return receiveCameras(state, action);
  default:
    return state;
};
```

Now, in my `receiveCameras` method, I want to make sure the second argument is of type `cameraActions.getCamerasSuccess`.

I can do something like this:

```ts
const receiveCameras = (state: CameraState, action: CameraAction) => {
  if (action.type !== getType(cameraActions.getCamerasSuccess)) {
    return;
  }
  
  // Now my action type is correct
}
```

I was wondering if I can specify the type when defining the parameter in the method to avoid doing that `if` check

Thank you

**Comment by piotrwitek** [comment]
Hello @farzadmf 
Currently not but it's because of TS v2.7 limitation.
Fortunately you will be able to do that in the new API 2.0 I'm currently working on, it will be released with TS 2.8 and to get action type type you will do this:
```ts
const receiveCameras = (state: CameraState, action: ReturnType<typeof cameraActions.getCamerasSuccess>) => {
...
```

I will open issue today for discussion/feedback on the API 2.0, new features like Symbols support, but also improvements to createAction (got rid of duplicated type argument finally :)) and probably push the working implementation to the next branch for testing.

**Comment by farzadmf** [comment]
Hello @piotrwitek thank you for your answer, So how I can I keep track when the new API version you mentioned and when it will available?

**Comment by piotrwitek** [comment]
2 days top I think, I'm heavily working on it

**Comment by duro** [comment]
@dziamid I have done so with success. I have a saga that looks like this:

```js
import { sessionActions as SA } from './actions'

function* setToken(action: ReturnType<typeof SA.setToken>) { }
```

Where `SA.setToken` is an action that was built with `typesafe-actions`

**Comment by dziamid** [comment]
@duro, sweet, was looking for the exact same use case. Are you using the version 1 of this library?

**Comment by duro** [comment]
Yes. I too am eager to see v2. I've been playing with TS2.8 and I can
totally see how it's going to make this library better.

**Comment by dziamid** [comment]
How exactly? Type and payload assertions are all I care about right now.

**Comment by piotrwitek** [comment]
Hi @dziamid, for example this: https://github.com/piotrwitek/typesafe-actions/issues/21#issuecomment-375331042

**Comment by piotrwitek** [comment]
Closing as issue seems to be unactionable.
