### ISSUE TITLE
ActionType is always never

### ISSUE THREAD

**Issue by antony2809** [piotrwitek/typesafe-actions#204]
I'm trying to follow the tutorial, and I don't know why when making de declaration of my type Actions, is always return never. So this doesn't allows me to use the helpers.

I have this file structure

`constants.ts`

```
export const LOGIN = '@authentication/LOGIN';
export const LOGGED_IN = '@authentication/LOGGED_IN';
export const LOGOUT = '@authentication/LOGOUT';
```

`actions.ts`
```
import { createAction } from 'typesafe-actions';
import { LOGIN } from './constants';

export const login = createAction(LOGIN, action => {
  return (email: string, password: string) => action({email, password});
});
```

`reducer.ts`
```
import { ActionType, getType } from 'typesafe-actions';
import * as actions from './auth.actions';

export type AuthenticationAction = ActionType<typeof authenticationActions>; // Here it's always of type never
```

I'm doing something wrong, because I couldn't find the solution for this.

Regards

**Comment by piotrwitek** [comment]
Hey @antony2809 
v4 or v5?

**Comment by antony2809** [comment]
V5

**Comment by piotrwitek** [comment]
This is incorrect syntax, please check new API:

```
export const login = createAction(LOGIN, action => {
  return (email: string, password: string) => action({email, password});
});
```

![Screen Shot 2019-10-29 at 9 53 15 PM](https://user-images.githubusercontent.com/739075/67808209-87afe200-fa96-11e9-8104-569f091f370c.png)

**Comment by mitsuruog** [comment]
@antony2809 I had the same issue just now.
I guess you are on the tutorial V4. (V5 tutorial seems under preparing)
please try on V4, then the above issue will be gone.
