### ISSUE TITLE
5.x release changelogs are not documented in the Releases list

### ISSUE THREAD

**Issue by IronSean** [piotrwitek/typesafe-actions#206]
## Description
There are no release notes or explanations for breaking changes/version bumps for any 5.x release currently on the Releases tab. And CHANGELOG.md indicates that is the location for changelog information.

## Steps to Reproduce
1. Go to releases tab

## Expected behavior
A list of breaking and non-breaking changes with each release

## Suggested solution(s)
Add release notes

**Comment by piotrwitek** [comment]
Yep, it's in progress.

**Comment by piotrwitek** [comment]
Closed by https://github.com/piotrwitek/typesafe-actions/releases/tag/v5.1.0
