### ISSUE TITLE
v5.1 has more breaking changes than are documented in the release

### ISSUE THREAD

**Issue by C-Higgins** [piotrwitek/typesafe-actions#209]
I just upgraded from 4.4.2 to 5.1.0, following the migration guide. I replaced the methods with their deprecated counterparts, and I was only using createStandardAction everywhere so it was simple. However the types were still broken after that. There were `type is 'unknown'` errors everywhere in the redux code, which I think stemmed back to the createReducer or the combineReducers not emitting the right type. RootState was suddenly full of `unknown`s as well.  I don't have a reproduction for this, but I think more must be breaking than just the action creator functions.

**Comment by piotrwitek** [comment]
Hey,
I'll need a reproduction case or it's impossible to do anything about your issues.

**Comment by mavajee** [comment]
@piotrwitek code from examples for createAsyncAction

![image](https://user-images.githubusercontent.com/10177998/68973786-39257600-0800-11ea-9144-347b9d4feb65.png)
![image](https://user-images.githubusercontent.com/10177998/68973814-45a9ce80-0800-11ea-84e7-4c5d2d088abf.png)

**Comment by C-Higgins** [comment]
I noticed that if I remove the type override in v4, I get the exact same error as I do when upgrading to v5. Perhaps this is not the correct way to override in v5.

Override:
```
declare module 'typesafe-actions' {
  interface Types {
    RootAction: RootAction;
  }
}
```

**Comment by piotrwitek** [comment]
@mavajee what you're showing is not possible because there are unit tests and it's working correctly. Please provide a full reproduction case in a new issue if you want me to look at it.

@C-Higgins the override is correct, check the similar issue here confirmed it's working: https://github.com/piotrwitek/typesafe-actions/issues/210#issuecomment-554508758

**Comment by tstelzer** [comment]
FYI: I had the same error. Problem was me not properly following the migration guide, and failing to do
```typescript
import { deprecated } from "typesafe-actions";
const { createAction, createStandardAction } = deprecated;
```
everywhere I was still using the old action creators. That lead to my root-action to be incorrectly typed, which in turn caused my root-reducer to be incorrectly typed.

**Comment by C-Higgins** [comment]
Found the problem. At some point in the past, the handleAction took a getType call as the first parameter, like so:

```js
createReducer(initialState as Readonly<typeof initialState>).handleAction(
  getType(someAction),
  (state, action) => ({}),
);
```

This works properly in 4.4.2. In 5.1.0, you must remove the getType function and just pass the action.

**Comment by piotrwitek** [comment]
@C-Higgins thanks a lot for investigating this issue.
I think you're right, the reason here is that `handleAction` was supporting string constants, but in v5 you can still do it but it has a separate handled called `handleType`.

I'll add it to the breaking changes, thanks a lot for help!

**Comment by timosnel** [comment]
@piotrwitek the issue mentioned by @mavajee happens when the TypeScript setting 'strictNullChecks' is set to false. I just ran into the same problem.

We're currently in the process of migrating to stricter TS settings, but in case someone else runs into this, at least they know the cause.

This is what the type signature looks like with strictNullChecks turned off:
![afbeelding](https://user-images.githubusercontent.com/10553072/76776342-e906f200-67a6-11ea-8bc6-dc86fa3ff84b.png)

**Comment by feimosi** [comment]
I can confirm the same happens in our project (`strictNullChecks` set to false).
It expects the payload and meta parameters.

This action creator 
```ts
const fetchUsers = createAsyncAction(
  'Fetch users / Loading',
  'Fetch users / Success',
  'Fetch users / Failure',
)<
  undefined,
  { users: number[] },
  { error: Error }
>();
```
is typed as:
```ts
const fetchUsers.request: (payload: unknown, meta: unknown) => 
	PayloadMetaAction<"Fetch users", unknown, unknown>
```
and fails with:
```
error TS2554: Expected 2 arguments, but got 0.
120   yield put(fetchUsers());
```

**Comment by hapablap21** [comment]
It looks like if you replace `undefined` in the createAsyncAction generic parameters with `[undefined, undefined]`, it behaves correctly.  I'm not sure if that's expected behavior, but it's suboptimal for action creators that don't need a parameter.

**Comment by alexkazantsev** [comment]
@hapablap21 thanks! you saved my day :)
