### ISSUE TITLE
isActionOf - Argument contains array with invalid element at index 0

### ISSUE THREAD

**Issue by ArielGueta** [piotrwitek/typesafe-actions#237]
I'm creating action and use it with `isActionOf` according to the docs:

```ts
import { isActionOf, action } from 'typesafe-actions';

export const ACTION = (id) => action('Name', { id });

actions$.pipe(
  filter(isActionOf(ACTION)),
)
```

But I get an error:

> Argument contains array with invalid element at index 0, it should be an action-creator instance from "typesafe-actions"

What am I missing?

Thanks.

"typescript": "~3.9.3"

**Comment by Lemmmy** [comment]
Care to share how you fixed it/why you closed the issue?

**Comment by ArielGueta** [comment]
I changed it to:

```ts
export const ACTION = (id) => createAction('Name', ({ id }) => ({ id }))();
```
