### ISSUE TITLE
handleAction allows return object with properties not pesent in the state type

### ISSUE THREAD

**Issue by zdila** [piotrwitek/typesafe-actions#253]
I am not sure if it is a bug or feature, but this compiles just OK:

```typescript
const action = { type: 'action1' as const };

function createAction() {
  return action;
}

type State = { foo: number };

createReducer<State, typeof action>({ foo: 1 }).handleAction(
  createAction,
  () => ({
    foo: 2,
    bar: 3 // bar is not in State
  }),
);
```
If it is the feature, why `handleAction` allows returning object with properties not present in the state type? This way the compiler will not catch some errors.

**Comment by ovidiu-balau** [comment]
Is there any fix for this? It renders `createReducer` useless for me if `handleAction` cannot understand its return type

**Comment by piotrwitek** [comment]
This is typescript limitation, doesn't have anything to do with the library. Just provide an explicit return type and it will work as expected.
