### ISSUE TITLE
Type 'undefined' is not assignable to type 'RouterState' in strict mode.

### ISSUE THREAD

**Issue by zdila** [piotrwitek/typesafe-actions#35]
I am using version 2.0 and `"strict": true` in `tsconfig.json`.

Code:
```
import { RouterState } from 'react-router-redux';
import { routerReducer } from 'react-router-redux';
import { combineReducers } from 'redux';
import { RootAction } from './actions';

export interface IRootState {
  router: RouterState;
}

export const rootReducer = combineReducers<IRootState, RootAction>({
  router: routerReducer,
});
```

Error:
```
Argument of type '{ router: Reducer<RouterState>; }' is not assignable to parameter of type 'ReducersMapObject<IRootState, RootAction>'.
  Types of property 'router' are incompatible.
    Type 'Reducer<RouterState>' is not assignable to type 'Reducer<RouterState, RootAction>'.
      Types of parameters 'state' and 'state' are incompatible.
        Type 'RouterState | undefined' is not assignable to type 'RouterState'.
          Type 'undefined' is not assignable to type 'RouterState'.
```

Workaround is to set `"strictFunctionTypes": false` in `tsconfig.json` (found it in https://github.com/ngrx/platform/issues/709).

**Comment by piotrwitek** [comment]
Sorry but following the error message this issue clearly has nothing to do with this library.

**Comment by zdila** [comment]
Could you help me how to modyfy my code to not to need `"strictFunctionTypes": false`. I'll appreciate also if you forward me to better place for support. Thanks in advance.

**Comment by piotrwitek** [comment]
It seems you have mismatched type definitions of react-router-redux and redux, you should investigate closely version you're using, I suspect you're using yarn which is very bugged in this regard and introduces a lot of duplicated packages, with JS you'll get away but with types there will be issues with compatibility of different versions

**Comment by zdila** [comment]
Thanks. I am using `npm` but I'll investigate according your suggestions.

**Comment by piotrwitek** [comment]
Please check if you are using redux@4 or even redux@4 types, this will clash because I think is still using redux@3

**Comment by zdila** [comment]
Relevant lines from our `package.json`:

    "react": "16.3.2",
    "react-dom": "16.3.2",
    "react-redux": "5.0.7",
    "react-router": "4.2.0",
    "react-router-dom": "4.2.2",
    "react-router-redux": "5.0.0-alpha.9",
    "redux": "4.0.0",
    "typesafe-actions": "2.0.0-1",
    "@types/react": "16.3.14",
    "@types/react-dom": "16.0.5",
    "@types/react-redux": "6.0.0",
    "@types/react-router-dom": "4.2.6",
    "@types/react-router-redux": "5.0.14",
```

**Comment by pdaddyo** [comment]
@zdila I'm having same issue - did you manage to resolve this? Thanks in advance.

**Comment by zdila** [comment]
@pdaddyo I am still using workaround mentioned in the issue description.
