### ISSUE TITLE
Doesn't export createStandardAction in 2.0.0-rc 

### ISSUE THREAD

**Issue by LucienLee** [piotrwitek/typesafe-actions#37]
I found that there isn't createStandardAction method when Installing typedafe-actions from npm.

In the release, it only export the following 

```
export * from './types';
export * from './get-type';
export * from './is-action-of';
export * from './create-action';
export * from './create-symbol-action';
export * from './build-action';
```

**Comment by LucienLee** [comment]
I found that it doesn't exist in @next but in 2.0.0-rc.1.

**Comment by piotrwitek** [comment]
Hi @LucienLee,
Actually you're right and this is a valid issue.
I should have add @next tag when publishing as well, will fix this in a moment :)
Thanks!

**Comment by piotrwitek** [comment]
Ok done: 
```
latest: 1.1.3
next: 2.0.0-rc.1
rc: 2.0.0-rc.1
test: 2.0.0-rc.1
```
:)
