### ISSUE TITLE
Question regarding action.type

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [piotrwitek/typesafe-actions#4]
Hey there, this looks like a cool project and it's something I would like to use.

This is probably a dumb question but how does the type-narrowing work in this example:

```js
switch (action.type) {
  // getter on every action creator function:
  case increment.getType!():
    return state + 1;
  // alternative helper function for more "FP" style:
  case getType(increment):
    return state + 1;

  default: return state;
}
```

I'm guessing you have to maintain a union type for all of your actions?

Something like

```js
type Action = typeof increment | typeof decrement | ...
```

**Comment by Andrew-Lahikainen** [comment]
Perhaps a complete example with a reducer that uses the action payload would help me understand

**Comment by piotrwitek** [comment]
@Andrew-Lahikainen hello, yes you need and union type of course and at the moment I'm working on a helper to easily create union types from action creators

In parallel I'm working on a really detailed complete guide which will be posted in my react-redux-ts guide with ready to use starter example project (https://github.com/piotrwitek/react-redux-typescript-guide)

I can use this issue to announce progress made on union type helper and docs/guide

**Comment by piotrwitek** [comment]
I added a new section named "Tutorial", which contain a thorough explanation of how to create `RootAction` union type

**Comment by Andrew-Lahikainen** [comment]
Awesome! That's really useful, cheers
