### ISSUE TITLE
Generic actions

### ISSUE THREAD

**Issue by abdurahmanus** [piotrwitek/typesafe-actions#41]
Hello, I have a set of actions and reducers which I want to reuse in several places in my app. I want to store similar data which generates with those actions and reducers in different places of redux store, so I need to parametrize somehow actions and reducers, for example, to add some prefix to all actions names in a set. Is it a good and possible idea? Or should I use some data in action's payload to differentiate actions?

**Comment by piotrwitek** [comment]
Hi, I would need more context to understand your solution. Could you please provide code examples with brief explanation for each of them

**Comment by abdurahmanus** [comment]
https://codesandbox.io/s/ympvlp0qnz

see src/features/test1 folder
I have 2 use cases:
1) actions1, reducer1
    async actions, shape of actions the same, but request and result types are different (number, Data1[] and string Data[2]).
    reducers logic identical, store only differentiates in types of data
2) set of actions (actions2, reducer2)
   I want to store data with identical shape in several parts of my app's store. To achive this. i have to duplicate actions (with different prefixes in action types) and duplicate logic in reducers.

How can I improve my code in order to avoid so many duplications
P.S. sory for my English)

**Comment by piotrwitek** [comment]
Ad 1) Seems like a parametrized factory function that will generate an action creators and generic reducer could work for such case. I don't have an example for that but you can find some examples for JS and use `typesafe-actions` inside factory use type inference and return typesafe results.

Ad 2) If actions payload is the same and reducer logic is the same, I would probably use meta data to differentiate when to update state in each part.

**Comment by abdurahmanus** [comment]
![image](https://user-images.githubusercontent.com/7404552/40255249-2f2119ee-5aef-11e8-9624-b86660e70cad.png)
I was trying to do it this way, but string concat results to incorect actions type (string instead of 'something/action1', 'something/action2'). I'm very new to typescript

**Comment by piotrwitek** [comment]
You always have to provide entire string literal, it's "static-types" so they are static by definition, and you're trying to make them dynamic, which is impossible

**Comment by piotrwitek** [comment]
Not actionable, closing.

**Comment by pushys** [comment]
Given the recent huge TypeScript [update](https://github.com/microsoft/TypeScript/pull/40336), I guess dynamic action types have become very possible now.
