### ISSUE TITLE
How do you write an action creator with a default parameter?

### ISSUE THREAD

**Issue by sylvanaar** [piotrwitek/typesafe-actions#50]
Had you considered parameter defaults in your design?

Right now I am doing:

`(payload: number = 1) => createStandardAction(CHANGE_VIEW)<number>()(payload)`

But it seems like it could be improved upon so you don't have to repeat the payload type.

Thanks for the best redux action typings around!

**Comment by piotrwitek** [comment]
Hey!
For your case you can use [action](https://github.com/piotrwitek/typesafe-actions#action) factory, which will provide equivalent result:
```ts
import { action } from 'typesafe-actions'
const changeView = (payload: number = 1) => action(CHANGE_VIEW, payload)
```
Is there any reason why you didn't use that?

**Comment by sylvanaar** [comment]
Thanks. I think I should have read the documentation a little more! The design is way more flexible that I thought. 

Thanks again!
