### ISSUE TITLE
Highlighting in code sandbox is broken

### ISSUE THREAD

**Issue by Krever** [piotrwitek/typesafe-actions#51]
Hey! I just started learning react/redux stuff, so apology if the question is stupid. 

When you open an example project [reducer.ts](https://codesandbox.io/s/github/piotrwitek/typesafe-actions-todo-app/tree/master/?module=%2Fsrc%2Ffeatures%2Ftodos%2Freducer.ts) file and wait for errors highlighting to appear you will see that `action.type` and more are marked as errors. I have the same behaviour in my local setup with vscode.

I assume its just tooling error but quite annoying one. Can it be somehow dealt with? Coming from scala I'm used to the editor not being able to follow my types but I hoped for the better in typescript :)

![screenshot-codesandbox io 2018 06 03 09-31-36](https://user-images.githubusercontent.com/2219224/40884276-ee6c956c-6710-11e8-85a5-98180a730f62.png)

**Comment by Krever** [comment]
Errors go away in my local setup when I switch from some defaults ts version (2.7.2) to the workspace one (2.8.3). Don't know about code sandbox though. Sorry for the noise, but maybe it will help someone in the future. Feel free to close the issue.

**Comment by piotrwitek** [comment]
Hey. yes sandbox doesn't support TS 2.8. At some point in the future they
should probably update it and fix this issue

**Comment by piotrwitek** [comment]
@Krever good news :) I see they updated codesandbox to more recent ver. of typescript and there are no errors for me as you highlighted :)

Closing the ticket, but feel free to confirm.
