### ISSUE TITLE
Expose getType() method for action creators

### ISSUE THREAD

**Issue by geakstr** [piotrwitek/typesafe-actions#55]
Hi! Thank you for this package, it's very useful.

Is it possible to expose `getType()` function or `type` property itself to the public API? I see that the implementation already here https://github.com/piotrwitek/typesafe-actions/blob/dac2f148e614dcef33ee576b970264194a859906/src/create-action.ts#L28

I checked (TS 2.9.1) and right now it's possible to do things like this:

```
switch (action.type) {
  case someAction().type: { // I don't like this extra action creation
    // action typed correctly here
    break;
  }
}
```

So, I suppose it will work with `getType()`/`type` too and it will be a bit more simpler in use — not need extra import for `getType`

**Comment by flq** [comment]
Um, getType() is exposed? I'm using it all the time...

**Comment by piotrwitek** [comment]
It's an implementation detail and I don't recommend using this.
The problem with it is that if you add some extra property to static type of action creator redux type constrains will be yelling at you, that's some limitation I bumped on in the past.

I could make it optional, but you will need to assert first to use it:
```ts
switch (action.type) {
  case someTypesafeAction.getType!(): {
    // action typed correctly here
    break;
  }
}
```
I still consider this as a bad practice and I cannot recommend this approach.

**Comment by geakstr** [comment]
Ok, got it, thanks
