### ISSUE TITLE
i can't get the origin action type in reducer

### ISSUE THREAD

**Issue by vegawong** [piotrwitek/typesafe-actions#57]
code like that:
![image](https://user-images.githubusercontent.com/17271745/41635878-c1b6eb42-747d-11e8-8e74-3d4d096ea779.png)
my action type like that:
![image](https://user-images.githubusercontent.com/17271745/41635889-d1bd1548-747d-11e8-9f71-314d00186c0b.png)
it can't get the origin action type via `switch & case`
is there any wrong in my code?

**Comment by piotrwitek** [comment]
Hi,
Please show how you create fetchDataSuccess function

**Comment by vegawong** [comment]
```javascript
export const fetchDataSuccess = createStandardAction(types.FETCH_DATA_SUCCESS)<
    PlainObject
>()
```

**Comment by vegawong** [comment]
I think it's typescript's problem;  it can only show the property all the union type has;  some action has not payload . so it would show the error.  when i change my actions all create as PayloadAction and it work!

**Comment by piotrwitek** [comment]
I understand, please could you also show contents of entire './actions'  module, I could tell you which action could be problematic

**Comment by vegawong** [comment]
![image](https://user-images.githubusercontent.com/17271745/41648288-0d0d1b0c-74ab-11e8-8eb3-f9c6f4eeacb3.png)
this is action & reducer file

**Comment by piotrwitek** [comment]
@vegawong I think you shouldn't be using never, it should be void, can you try it? If you take a look at docs it is always using void.

**Comment by vegawong** [comment]
nothing worked!    it also create as `EmptyAction` type that only as `type` property.  it can't work in union type.

**Comment by vegawong** [comment]
hello!   I had found out what's wrong with that?   but.... emmmm...   I has no idea to deal with.
if i did not use constant type from another module,and then actionCreator would get the collect type and  it work! like that:
![image](https://user-images.githubusercontent.com/17271745/41694529-4c00344c-753d-11e8-8324-1770a4c03ee8.png)

but, when is use the constant from another module, actionCreator can't get the collect type like that:

![image](https://user-images.githubusercontent.com/17271745/41694645-cfe938bc-753d-11e8-87af-3e986964a027.png)

**Comment by vegawong** [comment]
@piotrwitek oh my god！ It is my fault; my constant code like that:
```javascript
const PAGENAME = 'dzcf/Prescriptions'

export const FETCH_DATA = `${PAGENAME}/fetchData`

export const FETCH_DATA_SUCCESS = `${PAGENAME}/fetchDataSuccess`
```

I type the code use `String Template` and typescript is not suport this way for `String Literals`, so that it can't get the right value as type for `getType` function. thanks
