### ISSUE TITLE
Declare meta property with createAsyncAction

### ISSUE THREAD

**Issue by gerardmrk** [piotrwitek/typesafe-actions#61]
Is there a way to declare the meta property when using `createAsyncAction`? The docs does not mention anything about it.

**Comment by piotrwitek** [comment]
Could you describe what is this meta property?

**Comment by gerardmrk** [comment]
With the standard synchronous action, you're able to specify a mandatory type, an optional payload, and an optional meta payload. Judging from the typings and the documentations, you're not able to specify an optional meta payload for async actions. That's okay though, I realize I can just declare all the standard `request`, `success`, and `failure` actions and just use that with my custom async function, so I'll just close this issue. Thanks for this package btw it really helps

**Comment by piotrwitek** [comment]
@gerardmrk Thanks for explanation now I understood your issue. 
It would be possible to add an overloaded createAsyncAction, that would accept 6 type parameters but that would be really mouthful and I think only a few % of user would really use it. Could you post a snippet of your solution to this problem? Perhaps someone in the future will end up here so he could benefit from your help :)

**Comment by gerardmrk** [comment]
`store/session/action.ts`
```

import { createAction } from "typesafe-actions";

import { MiddlewareFlags } from "@client/store/middleware";
import { AuthTokens } from "@client/store/session/models";

export const loginPending = createAction(
  "session.loginPending",
  resolve => (flags: MiddlewareFlags) => resolve(undefined, flags)
);

export const loginSuccess = createAction(
  "session.loginSuccess",
  resolve => (tokens: AuthTokens, flags: MiddlewareFlags) => resolve(tokens, flags)
);

export const loginFailure = createAction(
  "session.loginFailure",
  resolve => (error: Error, flags: MiddlewareFlags) => resolve(error, flags)
);

/*
 * as opposed to (this is better, don't use my example above unless you need to declare meta):
 *
 * export const loginAsync = createAsyncAction(
 *   "session.login_request",
 *   "session.login_success",
 *   "session.login_failure"
 *  )<void, models.AuthTokens, Error>();
 */

//...
```

`store/session/async-actions.ts`
```
// ...

export const login = (usernameOrEmail: string, password: string, remember: boolean): StoreAsyncAction => async (dispatch: StoreDispatcher, getState: () => StoreState, api: API): Promise<void> => {
  dispatch(actions.loginPending({
    showLoader: "progress.logging_in"
  }));

  try {
    const authTokens: AuthTokens = await api.auth.authenticate(
      usernameOrEmail,
      password,
      remember
    );

    api.auth.cacheLocalSession(authTokens);

    dispatch(actions.loginSuccess(authTokens, {
      showLoader: false
    }));
  } catch (err) {
    dispatch(actions.loginFailure(<Error>err, {
      showLoader: false
    }));
  }
};

// ...
```
Here's what I did. Rather than using `createAsyncAction`, I created normal actions which will be called in the thunk action, so I can add the meta object.

If anyone's curious to what this is doing, I've setup a couple of middleware (functions that eavesdrop on / intercept every action sent to the store. If an action contains a ui flag in its meta property, the middleware will fire an action to the store to toggle that UI.

For reference:
https://github.com/gerardmrk/xo/blob/master/src/client/store/middleware.ts#L29

Hope this helps
