### ISSUE TITLE
Add support of optional payload/meta to `createAction` API

### ISSUE THREAD

**Issue by el-dav** [piotrwitek/typesafe-actions#71]
typesafe-actions v2.0.4
typescript v3.0.1

When defining a payload as optional or possibly undefined, the output action's type seems to loss awareness of this undefined type which leads to a loss of type safety. Example below:

```
import { createAction } from 'typesafe-actions';

interface Payload {
  a: number;
}
export const testAction = createAction('TEST_ACTION', resolve => (payload?: Payload) => resolve(payload));
global.console.log(testAction().payload.a) // no type error even though payload is undefined 
```

**Comment by piotrwitek** [comment]
After consideration I won't be working on this, maintenance cost is not worth the effort. There is much more higher priority feature-requests that I plan to invest my time on them because they target more common use-cases.
