### ISSUE TITLE
`getType` does not show type error for incompatible action-creator parameter

### ISSUE THREAD

**Issue by johnkorzhuk** [piotrwitek/typesafe-actions#80]
I'm getting the exact same error as #58. However I'm aware of the warning and I am doing exactly the the README says.

I'm on typescript version 3.0.3.

The types for `type` aren't being widened to strings:
https://d.pr/i/7I3H8B
https://d.pr/i/fyECRb

So in constants.ts:
```typescript
export const SET_REGISTER_REQUEST_SENT = "auth/SET_REGISTER_REQUEST_SENT";

export const SET_RESEND_ACTIVATION_SHOWN_REQUEST = "auth/SET_RESEND_ACTIVATION_SHOWN_REQUEST";

export const SET_LOADING_STATE = "auth/SET_LOADING_STATE";
```
actions.ts:
```typescript
import {
  SET_REGISTER_REQUEST_SENT,
  SET_RESEND_ACTIVATION_SHOWN_REQUEST,
  SET_LOADING_STATE
} from "./constants";

export const setRegisterRequestSent = () =>
  action(SET_REGISTER_REQUEST_SENT, null);

export const setResendActivationShown = (isResendShown: boolean) =>
  action(SET_RESEND_ACTIVATION_SHOWN_REQUEST, { isResendShown });


export const setLoadingState = (loading: boolean) =>
  action(SET_LOADING_STATE, { loading });
```

types.ts:
```typescript
import { ActionType } from "typesafe-actions";

import * as actions from "./actions";

export type Actions = ActionType<typeof actions>;
```

and reducer.ts:
```typescript
export default (state: State = DEFAULT_STATE, action: Actions) => {
  const { type, payload } = action;

  switch (type) {
      case getType(actions.setRegisterRequestSent):
        return {
        ...state,
        ui: {
          ...state.ui,
          isRegisterRequestSent: false
        }
      };

    case getType(actions.setResendActivationShown):
      return {
        ...state,
        ui: {
          ...state.ui,
          isResendActivationShown: payload.isResendShown
          // Property 'isResendShown' does not exist on type '{ isResendShown: boolean; } | { loading: boolean; }'.
          // Property 'isResendShown' does not exist on type '{ loading: boolean; }'.
        }
      };

    case getType(actions.setLoadingState):
      return {
        ...state,
        meta: {
          ...state.meta,
          loading: payload.loading
          // Property 'loading' does not exist on type '{ isResendShown: boolean; } | { loading: boolean; }'.
          // Property 'loading' does not exist on type '{ isResendShown: boolean; }'.
        }
      };
  }
}
```

**Comment by piotrwitek** [comment]
The code looks correct, I haven't tested on TS v3.0.0, but I'll be looking at this tomorrow.

**Comment by umairsiddique** [comment]
Hi, I am also running into the exact same issue.

**Comment by umairsiddique** [comment]
It was a mistake at my end. I wasn't letting the type guard do its thing. Once I moved my code under "case getType(actionCreatorFunctionName)", it worked its magic, and I could see payload just fine.

**Comment by johnkorzhuk** [comment]
> It was a mistake at my end. I wasn't letting the type guard do its thing. Once I moved my code under "case getType(actionCreatorFunctionName)", it worked its magic, and I could see payload just fine.

What version of ts are you on?

**Comment by umairsiddique** [comment]
I was on 3.0.3 earlier, but I upgraded to 3.1.1 later.

**Comment by Carl-Foster** [comment]
I added a comment to [here](https://github.com/piotrwitek/typesafe-actions/issues/83#issuecomment-427196613) which details why this doesn't work for the same issue.

Basically, the [action creator](https://github.com/piotrwitek/typesafe-actions/issues/83#issuecomment-427196613) does not have the niceness around it for the helpers like `getType` and `isActionOf`.
This is definitely a bug with the documentation, where this should be updated to be clearer for this creator.

**Comment by piotrwitek** [comment]
We have runtime exception for this kind of error but not on the type level because of some flexibility concerns.
To solve this kind of errors on type level for `getType` helper, parameters type could be constrained to accept only action creators created by createAction, then compiler would highlight this error.

I have to check if that will not interfere with redux types when used with redux specific scenarios.
