### ISSUE TITLE
Bug for getType？ first argument is not an instance of "typesafe-actions"

### ISSUE THREAD

**Issue by Adherentman** [piotrwitek/typesafe-actions#83]
## Describe the bug

I use getType() method but I got this error:
Uncaught Error: first argument is not an instance of "typesafe-actions"
## To Reproduce
actions :
```typescript
import { action } from 'typesafe-actions';
import { MemberActionTypes, MemberList } from './types';

export const queryMemberList = () => action(MemberActionTypes.queryMemberList);

export const queryMemberListSuccess = (memberList: MemberList[]) =>
action(MemberActionTypes.queryMemberListSuccess, memberList);
```

type: 
```typescript
export interface MemberList {
	_id: string;
	name: string;
	gender: string;
	mobile: string;
	site: string;
	exp: string;
}

export const enum MemberActionTypes {
	queryMemberList = 'member/QUERY_MEMBER_LIST',
	queryMemberListSuccess = 'member/QUERY_MEMBER_LIST_SUCCESS',
}

export interface MemberState {
	readonly memberList: MemberList[];
}

```
reducer :
```typescript
import * as Immutable from 'immutable';
import * as MemberAction from './actions';
import { ActionType, getType } from 'typesafe-actions';
import { MemberActionTypes, MemberState } from './types';
import { Reducer } from 'redux';

export type MembersAction = ActionType<typeof MemberAction>;

const initalState: Immutable.Map<string, MemberState> = Immutable.fromJS({
	memberList: [],
});

const reducer: Reducer<Immutable.Map<string, MemberState>, MembersAction> = (
	state = initalState,
	action: MembersAction
) => {
	switch (action.type) {
		// case MemberActionTypes.queryMemberListSuccess: {
		case getType(MemberAction.queryMemberListSuccess): {
			return state.set('memberList', Immutable.fromJS(action.payload));
		}
		default:
			return state;
	}
};

export { reducer as MemberReducer };

```

## Project Dependencies
- Typesafe-Actions Version: ^2.0.4
- TypeScript Version: ^3.1.1
- tsconfig.json:

```json
{
  "compilerOptions": {
    "removeComments": false,
    "module": "esnext",
    "target": "es5",
    "lib": [
      "es6",
      "dom",
    ],
    "sourceMap": true,
    "moduleResolution": "node",
    "allowUnreachableCode": false,
    "strict": true,
    "rootDir": ".",
    "jsx": "react",
    "outDir": "../dist/interface",
  },
  "include": ["**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules", "**/*.spec.ts"]
}

```
## Environment
- Browser and Version: chrome
- OS: macOs
- Node Version: 10.6.0
- Package Manager and Version: yarn 1.7.0

**Comment by Carl-Foster** [comment]
`getType` doesn't work with the plain [action creator](https://github.com/piotrwitek/typesafe-actions#--the-actions). With that method, you need to use the enum that you've defined in the switch statement.

If you want to keep using `getType`, you can use [createAction](https://github.com/piotrwitek/typesafe-actions#createaction).

**Comment by Adherentman** [comment]
@Carl-Foster Thank you for your timely feedback, It is not seen in the document.

**Comment by JoshMcCullough** [comment]
@Carl-Foster FYI It actually is/was in the docs at that point in time: https://github.com/piotrwitek/typesafe-actions/blob/df375a5c739c1aeeecdc43004c8ebc0f096c906c/README.md#1-classic-js-style-with-constants-ftw 

> ...but we're constrained to use constants (as in regular JS applications) because some of advanced action-helpers (getType, isActionOf) will not work with such action-creator...

**Comment by piotrwitek** [comment]
Hey @Adherentman, it is mentioned in the tutorial but I agree it should be more explicit especially in the API reference in some bold text.

You can create a new issue regarding that problem.

**Comment by Adherentman** [comment]
> Hey @Adherentman, it is mentioned in the tutorial but I agree it should be more explicit especially in the API reference in some bold text.
> 
> You can create a new issue regarding that problem.

yes, But now i know how to fix this problem. I will create a new issue tomorrow.

**Comment by nixxquality** [comment]
What is the reason that getType and isActionOf does not work with the simpler action creators?
It would be really nice if they did.

**Comment by piotrwitek** [comment]
It's a feature of this library through a meta property on action creator.
