### ISSUE TITLE
Warnings for "Cannot find source file '../src/*.ts" in Webpack with source-map-loader

### ISSUE THREAD

**Issue by ALTinners** [piotrwitek/typesafe-actions#9]
Running Webpack 3 (and possibly older ones) with the `source-map-loader` plugin causes warnings like
```
Cannot find source file '../src/index.ts'
```
to be emitted. 

This can be resolved by the user by modifying the module rule for `source-map-loader` in the webpack config to include 
```
exclude: [path.resolve(__dirname, './node_modules/typesafe-actions')]
```

This is similar to a bug I found [here](https://github.com/angular-redux/store/issues/64) - it appears their solution was to include the source files in the npm package.

Good package BTW - really helpful :)

**Comment by piotrwitek** [comment]
Hello @ALTinners,
Thanks for reporting the issue and guiding me with some hints.
I will include the sources with a package but I will need someone to help me test it, maybe you can help me?

I just published a new version with the fix: v1.1.1

PS: I'm really happy that you like the library :)

**Comment by ALTinners** [comment]
@piotrwitek I'll read over the source and see what I can do, but I can't promise much - I only have a couple of days before I am back in C++ land for work.

**Comment by piotrwitek** [comment]
@ALTinners I didn't mean you should read the source, I only wanted if you could check if the warnings are still there as I added sources to the npm package.
So I wanted to know if the warnings are gone when you remove this from your webpack config:
```
exclude: [path.resolve(__dirname, './node_modules/typesafe-actions')]
```

**Comment by piotrwitek** [comment]
@ALTinners as I'm not able to test it without a webpack config that can reproduce the error, I gonna close the issue

**Comment by codelovesme** [comment]
Easy to close
