### ISSUE TITLE
Add `toString` method to returned action creators

### ISSUE THREAD

**Issue by mAAdhaTTah** [piotrwitek/typesafe-actions#96]
## Is your feature request related to a problem?
I'm looking at migrating a codebase from redux-actions to typesafe-actions, as we're incrementally adopting TS and are currently using redux-actions. We're relying on the fact that redux-actions are coercible to strings to avoid creating string constants, so we're doing `action.type == reduxActionsCreator` in a few places in our .js files. Because typesafe-actions don't have this, we can't change our action creators without changing all those usages which aren't in .ts files so it makes it a bit more difficult to migrate.

## Describe a solution you'd like
Add a `toString` method that does the same thing as `getType`.

## Who does this impact? Who is this for?
Users of redux-actions looking to migrate to typesafe-actions as an incremental adoption.

## Describe alternatives you've considered
Not using typesafe-actions and just creating our actions the old-fashioned way.

## Additional context
I'd be willing to PR this is this is something you'd accept.

**Comment by piotrwitek** [comment]
Hey,
I think it is a sensible request. I need to check the code if there are any issues with type soundness in resulting action literal type, so union discrimination can still work with this approach.

**Comment by piotrwitek** [comment]
@mAAdhaTTah btw. is redux-actions creators coercion mechanics documented somewhere? Because I couldn't find it anywhere in the docs.

**Comment by mAAdhaTTah** [comment]
Do you have tests that cover that case?

It's not really documented explicitly but it's the only way handleActions could work. So it's an implementation detail we're taking advantage of in our code.
